### PR TITLE
Adapt Register to using the new Google Play Billing library

### PR DESCRIPTION
**Pull request by dextorer**
## Description 

Google's new [Play Billing Library](https://developer.android.com/google/play/billing/billing_java_kotlin) (PBL in short) is the new official approach to integrate in-app purchases, deprecating the need for manually relying on the `AIDL` files.

Due to the nature of how Register was originally implemented, migrating to PBL is not straightforward, given that they both wrap the same billing service through `AIDL`.

The goal would be to reuse as much code from PBL as possible, but to point to the Register billing service instead of the Play one.

This PR proposes an approach that satisfies the goal and, at the same time, highlights some improvements that could be made to PBL to ease the integration with third-party libraries, such as Register (in fact, having these improvements would simplify this very PR by a lot).

## Implementation

`BillingClient` is an abstract class, allowing multiple implementations to be created; PBL provides only one, called `BillingClientImpl`. Unfortunately, `BillingClientImpl` is package-private within `com.android.billingclient.api`, but we can replicate the package structure in Register and have visibility over that class.

Now that we have access to the main implementation of PBL, we would like to simply being able to have `BillingClientImpl` point to `RegisterService` instead of the Play one. Unfortunately, `BillingClientImpl` has many local variable declarations (i.e., not constants, not exposed in the `BillingClient` interface, not provided using functions, etc.) that makes it almost impossible to change, if not by using Reflection.
However, we can act as wrappers (a.k.a. man-in-the-middle) all the way up to the `Binder` implementation to "trick" PBL into thinking that it is communicating with the Play billing service, but it is talking to the Register service instead. To do so, we *simply* need to change all the package names, `Intent` actions and `Parcel` payload back and forth between the Play service and the Register service.
This operates under the assumption that the Register service exists and adheres to an AIDL interface that is compatible to the one shipped within PBL.

To know more about the actual implementation, see the `WrappedContext` class, `WrappedServiceConnection` class, and `WrappedBinder` class.

## Results

It works! We can seamlessly switch between the two providers, and it works just the same way as before.

## PBL improvements

Even though we pulled off this stunt, it doesn't mean that this is the ideal implementation for the integration. To be more specific, PBL could:
- expose the `Intent` actions and package names (e.g., declare them as protected fields of the abstract `BillingClient` class)
- expose the interface/stub object (e.g., declare it as a protected field of the abstract `BillingClient` class)
This would already be enough for providing a different "reference" to the billing service and to being able to provide our own implementation.

## Caveats

In order not to break the existing users when PBL updates with possibly breaking changes, we need to ship the PBL dependency in Register.

## What's missing

The old battery of tests was obsolete with regards to the new implementation, so I temporarily removed them. We can discuss what's the best way of rewriting them according to the new implementation.

## Credits

A huge thanks to [Eugenio](https://github.com/takhion) for helping me out on this ❤️

### CODE REVIEW

**Comment by dextorer** [comment]
CI is failing because

```
Caused by: org.gradle.api.GradleException: Failed to install the following Android SDK packages as some licences have not been accepted.
   build-tools;27.0.3 Android SDK Build-Tools 27.0.3
To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
```

**Comment by digitalbuddha** [comment]
This is amazing! Thank you so much for your hard work.  As for license stuff I think you need

```before_install:
  - yes | sdkmanager "platforms;android-27"```  

added to the Travis.yml

**Comment by digitalbuddha** [comment]
Sweet that work. 1 checkstyle violation remaining
[ant:checkstyle] [ERROR] /home/travis/build/NYTimes/Register/app/src/main/java/com/nytimes/android/external/register/BillingServiceStubImpl.java:46: Line is longer than 120 characters (found 131). [LineLength]

**Comment by dextorer** [comment]
I've rebased to clean the history a little bit (sorry, thought I'd run the tests after the refactoring but apparently I didn't). Now it should be good also on the CI side.

**Comment by wdziemia** [comment]
Checked the PR, and Im running into two issues:

1.) Im getting some strange behavior with the SKUs that come back (ConfigSkus). Sometimes Ill get only the subscription to return, other times both will return.

2.) I'm able to make a purchase but that purchase is not longer reflected in the SampleActivity. It looks like Pair.Second value in SampleActivity#checkPurchasesAndSkuDetails() always returns a list of 0 elements. 

Hopefully we can remove the register.json file in the near future too (because I had an issue with the wrong version of the JSON file 😀)

**Comment by dextorer** [comment]
I don't like how `SampleActivity` was wired up with the new approach (namely because I just wanted to see it working first). We can either refactor it on a separate PR or polish a little this approach, but there's tons of things that I'd like to do:
- move to Kotlin
- get rid of Guava for `ImmutableList`s
- Remove useless constants
- ...

My fear is that it might confuse what this PR is about. What do you think?

**Comment by goldstei** [comment]
I'm okay with these `SampleActivity` changes on this PR

**Comment by wdziemia** [comment]
@dextorer @goldstei  if the changes are small enough then no biggie! If not, I'd make core changes to the SampleApp that have to do with the PR and also convert to kotlin. The other things (guava, constants) can then be divided up and worked on concurrently by any of us.

**Comment by dextorer** [comment]
I pinpointed the last issue with the new integration!

`BillingServiceStubImpl` makes use of an injected instance of `SkuDetailsBundleBuilder`. `SkuDetailsBundleBuilder` exposes a `newBuilder()` method, that by design does not create a new instance of the class but rather just resets its internal fields. This makes it impossible to query for different product types at the same time.

For now, we need to serialize access to that object by fetching the SKU details sequentially. However, this is a serious limitation that we should be addressing as soon as possible.

**Comment by tiwiz** [comment]
@dextorer it looks good to go to me. For what concerns the serialisation issue you highlighted, one solution that comes to my mind is actually having the `newBuilder()` method return a new instance (that means converting it to a static method and pass all the previous data we need, more or less like the `copy` method in Kotlin), but I think that could be seen as an improvement or in a further release.

**Comment by dextorer** [comment]
Yeah but the whole thing feels dirty/wrong to me. We're injecting an instance that we then use to create other instances, as if it was static but it really isn't. We need to rethink the injection approach and/or the behavior of that class (e.g., "Can we make it stateless?", "Is it really a builder?", and so on and so forth).

**Comment by tiwiz** [comment]
@dextorer oh, yes, definitely, I did not really express myself as accurately as I wanted to, my apologies. In my mind, I was thinking of a broader refactor that would get rid of Immutables and Optionals as well, I just only thought of it instead of expressing it loud and clear, I'm sorry.

**Comment by Takhion** [comment]
@tiwiz I'm sorry, did you say Kotlin? :grin:

**Comment by tiwiz** [comment]
@Takhion of course I did, it was just hidden :-D

**Pull request merged**
